# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: p2p.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tp2p.proto\x12\x03p2p\"$\n\x0f\x44ownloadRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\"$\n\x10\x44ownloadResponse\x12\x10\n\x08\x66ile_url\x18\x01 \x01(\t2J\n\x0b\x46ileService\x12;\n\x0c\x44ownloadFile\x12\x14.p2p.DownloadRequest\x1a\x15.p2p.DownloadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'p2p_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DOWNLOADREQUEST']._serialized_start=18
  _globals['_DOWNLOADREQUEST']._serialized_end=54
  _globals['_DOWNLOADRESPONSE']._serialized_start=56
  _globals['_DOWNLOADRESPONSE']._serialized_end=92
  _globals['_FILESERVICE']._serialized_start=94
  _globals['_FILESERVICE']._serialized_end=168
# @@protoc_insertion_point(module_scope)
